[build]
  command = "npm run build && npm run convert-images && npm run optimize-html"
  publish = "."

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-image-optim"